### ISSUE TITLE
Typography Settings Filter

### ISSUE THREAD

**Issue by anteksiler** [valendesigns/option-tree#214]
Hi Derek,

Is this something that you can incorporate? Sometimes, I want to let the user change only the font-family or font-size, however right now, every setting is displayed when you add a typography field.

**Comment by YourBusyBee** [comment]
I would love some guidance on how to set this filter with an array of field ID's instead of just one (for instance, I'd like to disable a set of font options for all h elements (I'm afraid I'm still not as advanced as I'd like to be in figuring PHP out on my own. I'm getting there, but I'm just missing the mark on this one for sure).

**Comment by gerardbm** [comment]
Hi, @YourBusyBee.

That's a good idea, so I programmed it for my theme. Let's assume you have six ```typography``` options defined (one for each heading: h1, h2, h3, h4, h5, h6). On my theme, as example, I have six options with the following IDs ```heading_h1_typo```, ```heading_h2_typo```, ```heading_h3_typo```, ```heading_h4_typo```, ```heading_h5_typo``` and ```heading_h6_typo```.

Instead of making a filter for each heading —a lot of repetitive code— we can simplify the code using the constructor ```foreach```. This constructor is used to loop through each key/value of an array. So, the code will be repeated for each value of the array ```$headings```: six times.
```php
function remove_heading_fields ( $array, $field_id ) {
	$headings = array( 1, 2, 3, 4, 5, 6 );
	foreach ( $headings as $heading ) {
		if ( $field_id === 'heading_h' . $heading . '_typo' ) {
			$array = array(
				'font-color',
				'font-size',
				'line-height',
				);
		}
	}
	return $array;
}
add_filter( 'ot_recognized_typography_fields', 'remove_heading_fields', 10, 2 );
```
Of course, you can include all the font properties defined into the ```typography``` option: 'font-style', 'font-variant', 'font-weight', 'font-size', 'line-height', 'font-family', 'letter-spacing', 'text-decoration', 'text-transform', 'font-color'.

Regards.

**Comment by valendesigns** [comment]
You could potentially get better performance by not looping over the array for every single typography field. May I suggest this instead. The regular expression is very specific and will only match the 6 permutations of `heading_h1_typo` through `heading_h6_typo`.
```PHP
function remove_heading_fields( $fields, $field_id ) {
	if ( preg_match( '/\bheading_h([1-6]{1})_typo\b/i', $field_id ) ) {
		$fields = array(
			'font-color',
			'font-size',
			'line-height',
		);
	}
	return $fields;
}
add_filter( 'ot_recognized_typography_fields', 'remove_heading_fields', 10, 2 );
```

Granted I have not tested this code or benchmarked it. I just felt there were other options that could demonstrate what you're trying to do.

**Comment by gerardbm** [comment]
That's awesome, @valendesigns! Thanks, it's a very elegant solution :)

**Comment by YourBusyBee** [comment]
You guys are awesome. Thanks loads! (sorry I didn't have a chance to respond earlier)

**Comment by wp-organic** [comment]
> You could potentially get better performance by not looping over the array for every single typography field. May I suggest this instead. The regular expression is very specific and will only match the 6 permutations of `heading_h1_typo` through `heading_h6_typo`.
> 
> ```
> function remove_heading_fields( $fields, $field_id ) {
>     if ( preg_match( '/\bheading_h([1-6]{1})_typo\b/i', $field_id ) ) {
>         $fields = array(
>             'font-color',
>             'font-size',
>             'line-height',
>         );
>     }
>     return $fields;
> }
> add_filter( 'ot_recognized_typography_fields', 'remove_heading_fields', 10, 2 );
> ```
> 
> Granted I have not tested this code or benchmarked it. I just felt there were other options that could demonstrate what you're trying to do.

Very helpful for me!! 

Thank you for the response.
