### ISSUE TITLE
Feature Request: Restrict meta-box to specified page/post

### ISSUE THREAD

**Issue by sparkdevelopment** [valendesigns/option-tree#241]
Is it possible to add a 'slug' option at metabox level which would restrict the metabox to one page/post only?

I've done this by adding the option and then using the following code to implement the restriction:

```php
$admin_post_id = $_GET['post'];

if ( get_post( $admin_post_id )->post_name == $meta_box['slug'] || !$admin_post_id ) {
  ot_register_meta_box( $meta_box );
}
```

Note that I had to add the ```!$admin_post_id``` condition otherwise it would not save the data when submitted.

**Comment by valendesigns** [comment]
You can modify the following code to suite your needs, it's what I use for client work, but I typically know what things are going to be saved as so my personal version uses less code. You can either check against the slug or title, or really anything you want. I would prefer the slug, but it doesn't exist until the post is published so you will get better results using the title. There are other things you can use to identify the post since you have access to the `$post_id` in the URL params. For example, a page template or another OT meta value. The choice is yours.

```PHP
/**
 * Setup the meta boxes. 
 *
 * @return void
 */
function theme_name_meta_boxes() {

  // Get the current post ID
  $post_id = isset( $_GET['post'] ) ? $_GET['post'] : ( isset( $_POST['post_ID'] ) ? $_POST['post_ID'] : 0 );
  $post_data = get_post( $post_id, ARRAY_A );
  $slug = isset( $post_data['post_name'] ) ? $post_data['post_name'] : '';
  $title = isset( $post_data['post_title'] ) ? $post_data['post_title'] : '';

  $your_title_meta = array(
    'id'        => 'theme_name_meta',
    'title'     => __( 'Meta', 'theme-name' ),
    'desc'      => '',
    'pages'     => array( 'post' ),
    'context'   => 'normal',
    'priority'  => 'high',
    'fields'    => array(
      array(
        'id'          => 'sub_title',
        'label'       => __( 'Sub Title', 'theme-name' ),
        'type'        => 'text'
      )
    )
  );
  
  if ( function_exists( 'ot_register_meta_box' ) && ( $slug == 'your-title' || $title == 'Your Title' ) )
    ot_register_meta_box( $your_title_meta );

}
add_action( 'admin_init', 'theme_name_meta_boxes' );
```
