### ISSUE TITLE
Dynamic CSS with Wordpress Multisite

### ISSUE THREAD

**Issue by coleh3** [valendesigns/option-tree#356]
Is there a way to use the same theme on a multisite network with this plugin? Right now with the dynamic.css file if someone makes a color choice it appears to effect the entire network.

Is there a work-around to this that you could please help me with?

Great plugin and thanks for making it!

**Comment by CapitalH** [comment]
This is kind of very important. @valendesigns Is there any way to do this?
I am using OT in theme mode and I was wondering if I could use the dynamic.css func on multisite level. Right now when an option that writes to dynamic.css field is changed, it changes the options for all the network since the dynamic.css is linked to all of them.

**Comment by valendesigns** [comment]
Couldn't you add a filter to change the file path for each site? I don't really see a network wide solution in your particular situation happening any other way.

**Comment by CapitalH** [comment]
@valendesigns I have already tried the filter for according to your answer to my dynamic.less question, but could not get it right, I don't know which part I'm doing wrong.

I have explained it here more: https://github.com/valendesigns/option-tree/issues/423

Maybe if you provide a practical example it would help me resolve both of my issues.

**Comment by valendesigns** [comment]
I thought maybe you could try this..
```PHP
if ( ! function_exists( 'cfw_css_option_file_path' ) ) {
    function cfw_css_option_file_path( $filepath ) {
        if ( is_multisite() ) {
          $filepath = get_stylesheet_directory() . '/dynamic-' . get_current_blog_id() . '.css';
        }
        return $filepath;
    }
}
add_filter( 'css_option_file_path', 'cfw_css_option_file_path' );
```
However, after looking into it, the issue then becomes the `ot_load_dynamic_css` functions problem. It doesn't know to only load the one file, it loops over all of them and enqueue's everything in the `ot_css_file_paths` array. Maybe a second filter added to the `ot_load_dynamic_css` would be needed to limit which files are enqueued?  

If I add a filter like so...
```PHP
/* grab a copy of the paths */
$ot_css_file_paths = apply_filter( 'ot_load_dynamic_css', get_option( 'ot_css_file_paths', array() ) );
```

You could then add a second filter to limit the array but would need to add the field ID manually because that function in unaware of the field.
```PHP
if ( ! function_exists( 'cfw_ot_load_dynamic_css' ) ) {
    function cfw_ot_load_dynamic_css( $paths ) {
        if ( is_multisite() ) {
          $paths = array();
          $paths['your_field_id'] = get_stylesheet_directory() . '/dynamic-' . get_current_blog_id() . '.css';
        }
        return $paths;
    }
}
add_filter( 'ot_load_dynamic_css', 'cfw_ot_load_dynamic_css' );
```

However, another option would be to change where the array is stored for multisite like this, but needs to be tested before it could be added to the codebase.
```PHP
if ( is_multisite() ) {
  $ot_css_file_paths = get_blog_option( get_current_blog_id(), 'ot_css_file_paths', array() );
} else {
  $ot_css_file_paths = get_option( 'ot_css_file_paths', array() );
}
```

It's more work on my end, but I think the second option is a bit more seamless for everyone using the `css_option_file_path` filter already. Any thought?

**Comment by CapitalH** [comment]
This would exactly be more work on your side, I hope we can have it in 2.5


Could you please answer my question on dynamic.less too? You have closed that issue and I think you don't get notified I reply there.
https://github.com/valendesigns/option-tree/issues/423

**Comment by valendesigns** [comment]
So in `ot_load_dynamic_css` where it grabs the `ot_css_file_paths` option, if I change that, like I mentioned above, you would need to save the theme again before the paths were updated. However if I did the following it could use the network wide paths as the default value. Do you have any thoughts on how this will effect current users?

```PHP
/* grab a copy of the paths */
$ot_css_file_paths = get_option( 'ot_css_file_paths', array() );
if ( is_multisite() ) {
  $ot_css_file_paths = get_blog_option( get_current_blog_id(), 'ot_css_file_paths', $ot_css_file_paths );
}
```

**Comment by valendesigns** [comment]
@CapitalH I need to know if you can test this change once I add it to 2.5.0? Please respond back ASAP.

**Comment by valendesigns** [comment]
You can test these changes in PR #449

**Comment by bchalker** [comment]
Hey Derek - first off. Love OT...it works wonderfully in my multisite template. I am unable to get this dynamic.css to work as I need, though, so I currently have the options pulled into the theme as embedded css (I know). My multisite environment is set up as subdomains and the sites are created automatically when a user signs up. Am I understanding the above comments correctly, that I need to "manually" have the dynamic-BLOG ID css files created for this approach to work?

**Comment by CapitalH** [comment]
@bchalker Yes you will need to manually create those files, unless you write something with php that can create the files based on the new blog ID and hook it to the multisite blog creation action (if there is any)
