### ISSUE TITLE
OptionTree and Visual Composer - get_custom_field stripped with Frontend Editor

### ISSUE THREAD

**Issue by ThemeIsland** [valendesigns/option-tree#375]
Hi All,

I have a customer who has pointed out a slight bug in either Visual Composer, OptionTree, or both. It's also possible it our theme, and I am more than happy to hear any thought's you have on this. Also, is anyone else having this issue with Visual Composer and OptionTree meta-box options? Here's the example walkthrough on replicating the issue: 

First, we load OptionTree, our theme options file, and our meta-boxes file:
<pre>
add_filter( 'ot_theme_mode', '__return_true' ); 
	add_filter( 'ot_show_pages', '__return_true' );
	add_filter( 'ot_show_options_ui', '__return_true' );
	add_filter( 'ot_show_settings_import', '__return_true' );
	add_filter( 'ot_show_settings_export', '__return_true' );
	add_filter( 'ot_show_new_layout', '__return_false' );
	add_filter( 'ot_show_docs', '__return_true' );

	// LOAD IT UP
	require_once( trailingslashit( get_template_directory() ) . '/mythology-core/option-tree/ot-loader.php' ); // Load OptionTree.

	// LOAD THEME OPTIONS & META BOXES FOR POSTS/PAGES
	include_once( 'functions/admin/skeleton-theme-options.php' );
	include_once( 'functions/admin/skeleton-meta-boxes.php' );
</pre>

Then in skeleton-meta-boxes.php we have add our options (for simplicity, I've limited this to one): 

<pre>
add_action( 'admin_init', 'custom_meta_boxes' );

function custom_meta_boxes() {

  $page_options = array(
    'id'        => 'page_options',
    'title'     => 'Skeleton Page Options',
    'desc'      => '',
    'pages'     => array( 'page' ),
    'context'   => 'normal',
    'priority'  => 'high',
    'fields'    => array(
         
    
    array(
    	'id' => 'show_title',
		'label' => 'Show the Page Title?',			
		'desc' => 'Do you want to hide the page title from view? Leave this blank to display it by default.',					
		'type' => 'select',					
		'std' => '',
		'class' => '',
      	'choices'     => array( 
          array(
            'value'       => 'Yes',
            'label'       => 'Yes',
            'src'         => ''
          ),
      	  array(
            'value'       => 'No',
            'label'       => 'No',
            'src'         => ''
          )          
        ),
	),

/* ================= */

ot_register_meta_box( $page_options );
}
</pre>

Then we're adding this to our page.php file: 

<pre>
if(get_custom_field('show_title') == 'Yes') :
	// Display Title Markup
endif;
</pre>

Okay, this works great when using the standard page editor via WordPress and also works in conjunction with the Visual Composer "Backend Editor."

The issue arises when the Visual Composer "Frontend Editor" is used. Open the Frontend Editor > click Update (still fine) > then X out of the editor - it actually removes the options that are being set from the traditional page options. If you navigate back to the Page, you'll find the options are still set... Then if you hit update (on the backend), reload the page on the front, and all is well again. 

I tested this issue out on several other test installs with several different themes. Here is a video walkthrough provided by our theme user (in her case, the issues are sidebar options using get_custom_field, but the process is the same):

https://drive.google.com/file/d/0B9aqb4Rj-uH3ODRaM0NhQ3FySnM/edit?usp=sharing

We filed this with Visual Composer and this is what they said: 

<pre>
I just heard back from our development team regarding this issue. It looks like you use different patterns for sidebar and meta box in bottom. If in backend I check display title "NO", after update in frontend at the backend we will see correct result "display title: NO". But if I do the same in sidebar for example content alignment "center" and publish in frontend it reset value to "left". We apologize, but you might be using an invalid WordPress framework methods to save values
</pre>

This only tells me that the option values are being stripped on the frontend, but are still saved on the backend.

Please let us know if this is a compatibility issue between OptionTree and Visual Composer, or if I'm overlooking something or doing something incorrectly on my end. 

Cheers!
Charlie

**Comment by madzathemes** [comment]
Hi, Valendesigns

Please fix this issue!

I also have VC and OptionTree compatible problem.

From start I get this problem in my themes, then I just disabled Front End VC Editor function from my themes, but now my ThemeForest clients get angry for this (VC plugin now is TopSeeling plugin in CodeCanyon). 

If you need some help from me! Please ask! :)

**Comment by valendesigns** [comment]
@madzathemes I don't have a copy of the plugin or experience with the code base to really do much about this issue. Before I can even attempt to fix it I would need a copy of the plugin and a better understanding of what the issue is. If you have any ideas on how to fix it, that would be a big help, as well. I can't get to it for the 2.5.0 release on Monday, unless someone can fix it and I can verify it's working by no later than the end of tomorrow night PST. Which leaves very little time.

**Comment by atomixstar** [comment]
Hello, I also found the same issue, when I update the page from "Frontend Editor" the option-tree meta boxes are not save. Any help to fix this? I can send you the plugin.

Thank you

**Comment by valendesigns** [comment]
Send it to derek@valendesigns.com and I'll take a look when I get some time today or tomorrow.

**Comment by atomixstar** [comment]
Thank you so much, I just send you.

**Comment by madzathemes** [comment]
Hi Valendesigns!

Did you get this issue? Any date for this fix?

**Comment by Theme20** [comment]
Hi,

Any update on this ?! 

Also Textarea type inside option-tree doesn't show "back-end" and "front-end" button of visual composer, i've asked from VC author but he told me this is issue from option-tree. 

Thanks.

**Comment by valendesigns** [comment]
OptionTree doesn't do anything odd with meta boxes. It creates them using the WordPress API. The fact that Visual Composer destroys the values of the meta boxes on the front end after you save is in fact an issue with both plugins. Basically, the issue is that VC is destroying the meta box values indirectly because it doesn't pass OT's saved meta box `$_POST` values and makes OT think they are all set to empty. I've fixed it by exiting the meta box save routine in OT when `$_POST['vc_inline'] == true`. It will now stop destroying the data. 

Everyone! Please test hotfix-2.5.4 to verify. This release is going out today, so time is of the essence.

@Theme20 They said the issue is from OptionTree huh? That is not a valuable answer and honestly, a bit arrogant. Why would I need to add the VC button via OptionTree. Should I add every plugins button? I create textareas with the `wp_editor` function, and include the `ot_quicktags` filter for this very situation. If you need to add buttons, try that filter out. This isn't really an issue at all, or one with OptionTree for that matter. It's just that you need to add some filters. Also, I would not add those buttons to the editor because you cannot edit OT meta boxes via the VC front-end editor anyhow. So what purpose would that serve?

Cheers!
