### ISSUE TITLE
In OptionTree 2.4.2 GET themes.php?page=ot-theme-options LOADING ISSUE

### ISSUE THREAD

**Issue by Marinski** [valendesigns/option-tree#388]
Hi there guys.

I have been using OptionTree in THEME MODE for a custom WordPress theme, that I am currently building. But annoying loading issue appeared recently, related with Theme Options page in administration. When i open Theme Options ( GET request to themes.php?page=ot-theme-options ), loading breaks at beginning and slows opening of the options panel.

Here is a screenshot --> http://prntscr.com/4ov14k

There are some loading events that in my opinion slow down everything. I have noticed that during the loading of this specific page, "numeric-slider" option type is not showing its movable part of the slider (img1), and after 2-3 seconds break it is now visible (img2).

img1 --> http://prntscr.com/4ouyui
img2 --> http://prntscr.com/4ouz33

I also use Theme Mentor plugin that says colorpicker and date-picker script tags should be included on wp_enqueue_scripts or admin_enqueue_scripts instead of embedded directly at file option-tree/includes/ot-functions-option-types.php.

That's why recent days I am investigating a script issue, linked with inline scripts in ot-functions-option-types.php.

My issue is similar to this --> https://github.com/valendesigns/option-tree/issues/43

P.S. I have tested in latest Firefox, Chrome and IE - all gave me the same issue, just different browsers go through it in different way.

**Comment by valendesigns** [comment]
Not much movement on this issue yet, but I just did a quick check to see what would happen if the theme options page was completely blank by returning `false` before it's shown and there isn't much difference between the two, only about 250ms in my setup with 40+ options. So it's probably the queries before the page is rendered that is causing the issue. Food for thought.

**Comment by gerardbm** [comment]
@valendesigns, I've been thinking about it lately and I did some tests. In my case, it seems the issue is caused before the large select boxes are rendered. When it's loading, it shows partially the page (for example the sections and the tab type without styles), but it waits some seconds, and at the end it displays the select boxes. If I remove the options containing large select boxes, the page load is faster.

My theme has +120 options. The load time is relatively fast when I remove the options containing huge select boxes. For example, every 'typography' type has two large select boxes with +150 values each one (font-size and line-height). The 'google-fonts' type has a large array, also; about 671 fonts.

I show you the results of my tests. I hope it is useful for you.

My test is the following: I remove the options containing large arrays and I will add them after every load time test. The load time test is using Chrome Inspector in Localhost:

First one, without typography types, and without google-fonts type:

3.5 s (DOM 2.7 s).

Here I add one typography option:

3.8 s (DOM 2.9 s). It's between 200-300 miliseconds more.

To be sure, I add a new typography option:

4.0 s (DOM 3.15 s).

I want to check if it happens due to the font-size and the line-height arrays (+150 values each one), so I filter them in a new typography option:

```php
function remove_fields ($array, $field_id) {
	if ( 0 === strpos($field_id, 'heading_h6') ) {
		$array = array('font-size', 'line-height');
	}
	return $array;
}
add_filter( 'ot_recognized_typography_fields', 'remove_fields', 10, 2 );
```

The result:
4.15 s (DOM 3.3 s).

To be sure, I repeat the last step: added new typography option that displays onlye the font-size and the line-height:

4.45 s (DOM 3.5 s).

It seems the large arrays slow down the load page. I add the 'google-fonts' type (I have one option with two default values, so it will display two select boxes with ~671 values each one):

5.0 s (DOM 4.0 s).

After 5 options added (2 of them partially filtered), I decide to add the rest of my typography options: 9 typography options type displaying only the font-size and the line-height. That means, 18 new select boxes with +150 values every one:

6.2 s (DOM 5.0 s).

**Just a few typography options (14) changed the page load from 3.5 s to 6.2 s. The difference is huge when the first 3.5 s load 106 options (86.8% of the options).**

In this last test I remove the google-fonts option and I filter the font-size and the line-height fields to remove all their values from my 13 typography options:

```php
function edit_ot_options_line_height( $line_height ) {
	$line_height = array("Value");
	return $line_height;
}
add_filter( 'ot_recognized_line_heights', 'edit_ot_options_line_height', 10, 2 );

function edit_ot_options_font_size( $font_size ) {
	$font_size = array("Value");
	return $font_size;
}
add_filter( 'ot_recognized_font_sizes', 'edit_ot_options_font_size', 10, 2 );
```

The result is: 4.1 s (DOM 3.3 s). It's close to the first and the second tests!

Hope it helps!
