### ISSUE TITLE
Background Color Opacity?

### ISSUE THREAD

**Issue by anteksiler** [valendesigns/option-tree#459]
I thought the colorpicker opacity would be added to all colorpickers like WP default colorpicker. Anyone has any idea how we can incorporate this?

**Comment by valendesigns** [comment]
In retrospect that would have been better. I don't have time to change it now, since it's already released. However, I did see an implementation that I can use to merge the functionality into all colorpickers for possibly 2.5.2 and add a compatibly function to convert this option type at that point. Not ideal but I'm extremely busy ATM so it has to wait.

**Comment by valendesigns** [comment]
Overhauled the new Colorpicker Opacity option type. Please test it on the hotfix-2.5.1 branch.

**Comment by valendesigns** [comment]
Just add `ot-colorpicker-opacity` to the class argument when creating your background option.

**Comment by anteksiler** [comment]
Hi @valendesigns, could you give me an example?

Currently using:
```
array(
        'label'       => 'Bar Background',
        'id'          => 'bar_bg',
        'type'        => 'background',
        'desc'        => 'Background settings for the bars on the side, also includes footer.',
        'section'     => 'customization'
      ),
```

**Comment by valendesigns** [comment]
I'm on my phone so i'd prefer not to. Just add a class key to that array and set the value to the css class I mentioned above. It will add that class to all the BG form elements but the opacity is initiated only on the colorpicker.

**Comment by anteksiler** [comment]
Thanks @valendesigns , much appreciated

**Comment by valendesigns** [comment]
No problem. Happy to help.
