### ISSUE TITLE
Request: Add inherit fallback to link-color in dynamic.css

### ISSUE THREAD

**Issue by johnh10** [valendesigns/option-tree#469]
I'm using a link-color type with id 'site_anchor_color' and in my css type I'm using the rules

body {
a:link { color: {{site_anchor_colors|link}}; }
a:hover { color: {{site_anchor_colors|hover}}; }
a:active { color: {{site_anchor_colors|active}}; }
a:visited { color: {{site_anchor_colors|visited}}; }
a:focus { color: {{site_anchor_colors|focus}}; }
}

It would be great if I could replace it with just

body { {{site_anchor_colors}} }

Currently, using just {{site_anchor_colors}} prints out Array.

**Comment by valendesigns** [comment]
I'll add this to 2.5.2. Thanks for the bug report.

**Comment by johnh10** [comment]
Related: using type 'border' outputs just the values to the css type so I currently have to use
.class-field { border: {{class-border}} }
and if the end-user doesn't set class-border the dynamic.css would have
.class-field { border: }

Would it be better to include the 'border:' prefix as well when processing the css type so I only have to use
.class-field { {{class-border}} }
?

**Comment by valendesigns** [comment]
Sorry for the delay, I'll work 2.5.2 this week and hopefully have it out on Monday.

**Comment by valendesigns** [comment]
I have some backwards compatibility concerns with making some of these changes. Also, please create multiple issues. It's difficult to track progress when you have three separate issues in one ticket.

As for the first and original issue. The CSS above is not valid it should be
```PHP
body a:link { color: {{site_anchor_colors|link}}; }
body a:hover { color: {{site_anchor_colors|hover}}; }
body a:active { color: {{site_anchor_colors|active}}; }
body a:visited { color: {{site_anchor_colors|visited}}; }
body a:focus { color: {{site_anchor_colors|focus}}; }
```

Unfortunately, without a pretty big overhaul and making a lot of assumptions in `ot_insert_css_with_markers` about what the selector is, this seems like something that you'll just have to live with. I don't see a clean way to grab the previous selector because there are so many ways someone could be writing their CSS and using a regex might not be reliable enough.

**Comment by johnh10** [comment]
Hmm then would it be possible to use 'inherit' if the user doesn't set a value?

body a:link { color: inherit; }
instead of
body a:link { color: ; }

**Comment by valendesigns** [comment]
That is a possibility. I would need to test that a bit to make sure it doesn't cause any issue, but is certainly promising.

**Comment by valendesigns** [comment]
This has been added to the 2.5.2 branch.
