### ISSUE TITLE
Conditional issue: dynamic.css file lost when stock theme is updated.

### ISSUE THREAD

**Issue by johnh10** [valendesigns/option-tree#471]
Scenario: A stock theme using Option Tree with a css type that creates a dynamic.css file.

Since the end user isn't using a child theme, when the stock theme is updated, the dynamic.css file is lost. The end user would have to know and remember to go into Option Tree and save settings again to recreate the dynamic.css file after a theme update.

Is it possible to hook into something like an 'after theme update' action and then, if not a child theme, to process any css type to create the dynamic.css file automatically?

**Comment by valendesigns** [comment]
This could probably done but I feel might be beyond the scope of OT to handle. As well, this is the expected behavior when upgrading themes that the theme files will be replaced. 

An alternative solution might be an admin nag which says you need to save your theme options to rebuild the `dynamic.css` file after a theme upgrade, but only if the theme has CSS options.
