### ISSUE TITLE
Google font Issue output font family values like google's recommended format?

### ISSUE THREAD

**Issue by Ansif** [valendesigns/option-tree#566]
Hi,

Thanks again for the great plugin! :+1: 

For example if i use PT sans :
https://www.google.com/fonts#UsePlace:use/Collection:PT+Sans

Google recommend to use following css format :
<pre>font-family: 'PT Sans', sans-serif;</pre>

But it'll echo like : 
![screen shot 2015-10-12 at 1 45 17 pm](https://cloud.githubusercontent.com/assets/5621180/10423804/827203e6-70e7-11e5-9dd5-acc73f9b47e4.png)

My dynamic-style.php file :
![screen shot 2015-10-12 at 1 45 36 pm](https://cloud.githubusercontent.com/assets/5621180/10423817/8e7613b2-70e7-11e5-9e9d-a2388400d5ce.png)

Thanks again. :)

Regards,
Ansif

**Comment by gerardbm** [comment]
Hi, Ansif.

The 'font-family' value is not designed to be displayed directly. You will need to create a PHP function to parse the 'font-family' value. For example (code by @valendesigns from [here](https://github.com/valendesigns/option-tree/pull/444#issuecomment-72634452)):

```php
if ( ! empty( $typo_setting['font-family'] ) ) {
  $ot_google_fonts = get_theme_mod( 'ot_google_fonts', array() );
  if ( isset( $ot_google_fonts[$typo_setting['font-family']]['family'] ) ) {
    $style .= 'font-family: "' . $ot_google_fonts[$typo_setting['font-family']]['family'] . '";';
  } else {
    $style .= 'font-family: "' . $typo_setting['font-family'] . '";';
  }
}
```
It helped me. Moreover, when you save the 'body-font' option in the ```$body_font``` variable, it would be good if you get the default values, as well, so you won't have a broken design after a fresh install of your theme. For example:
```php
$body_typo = ot_get_option( 'body_typo', array(
	"font-style" => "normal",
	"font-variant" => "normal",
	"font-weight" => "400",
	"font-size" => "13px",
	"line-height" => "20px",
	"font-family" => "opensans",
	"letter-spacing" => "0em",
	"text-decoration" => "none",
	"text-transform" => "none",
	"font-color" => "",
	)
);
```
Otherwise, you can use the dynamic.css method (create a dynamic.css file in your root theme folder and create a CSS option type. This option will enqueue the CSS file in the head. Put your code in the CSS option and save).

The first method will interpret the PHP code in the server after every page load to generate and print the CSS directly in the ```head```, while this second method will generate the ```dynamic.css``` file only when you save the options.

Regards.
