### ISSUE TITLE
Google Fonts Issue

### ISSUE THREAD

**Issue by InspiryThemes** [valendesigns/option-tree#576]
Hi,
Hope your are doing well. We are facing Google fonts stylesheet issue. Somehow, plugin has stopped adding fonts stylesheet in page head.

We are using "Shadows Into Light" font...

http://prntscr.com/93asl1

and the CSS is working fine...

http://prntscr.com/93at6s

But the style sheet of this font is missing.

Kindly check it asap.

Thanks in Adavnce

**Comment by BassemN** [comment]
@InspiryThemes  Check this https://github.com/valendesigns/option-tree/pull/444#issuecomment-72634452

**Comment by InspiryThemes** [comment]
Hi Derek,
               Thanks for your response. I read this #444 (comment). But my issue not related to this. Because i haven't issue with subset, variant, Styles or font-family. My issue is, the Google font api not  including the related font stylesheet at all.  As i mentioned earlier, We are using "Shadows Into Light" font...

http://prntscr.com/93asl1

and the CSS is working fine...

http://prntscr.com/93at6s

But the style sheet of this font is missing. 

So, please check it on your own.

Thanks a lot

**Comment by valendesigns** [comment]
@InspiryThemes How are you including the CSS in your theme?

**Comment by InspiryThemes** [comment]
Hi,
     Here is a screenshot of css

http://prntscr.com/96og51

Here is output of css:

http://prntscr.com/96oi7g

You can see that all font-size, color, weight working fine. But the Font-family is not implementing correctly. That's why it is not looking as it should be. Here is a correct look of this font

http://prntscr.com/96ojwd

All was working fine. This problem pops up some days ago, may be a week ago.  When one of our theme user report this issue.

Thanks for all your time

**Comment by valendesigns** [comment]
The comment @BassemN mentioned above is 100% the issue. You're code is using the font key that is saved in the database as the `font-family` value and it's failing to render because of it. Please read the comment that was linked to again and you will see there is a way to grab the family using the key.

**Comment by InspiryThemes** [comment]
Hi,
     OK!    I'm using your recommended way. Here is the code screenshot:

http://prntscr.com/96p09k

Here is the output 

http://prntscr.com/96p1pd

I'm sending you the source of this file in which you see there is no stylesheet of this font

http://jmp.sh/aCZ9ZVd

you can download and check by yourself. I know you have many things to do brother but this is a serious issue. Please help me.

Thanks for all your time Brother

**Comment by BassemN** [comment]
@InspiryThemes what is the link for stylesheet inserted to head with ot-google-fonts-css id?

**Comment by InspiryThemes** [comment]
Hi,
    Plugin should be added this stylesheet in header.

<link href='https://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>

You know when we add a google font then it's stylesheet must be added in head but when we select a font through your plugin then everything is going good but plugin is not adding stylesheet link of this font in head.

We are using these two fonts "Droid" and "Pacifico". you can find in my given source file these two stylesheets by searching these phrases Droid and Pacifico. For your note, these two fonts are not coming from your plugin. Both  are added manually as theme fonts.

I'm trying to say that plugin should be add this stylesheet link

<link href='https://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>

in head. You can check by searching this phrase Shadows. You will find the font styles but not the sheet link


Thanks a lot

**Comment by valendesigns** [comment]
OptionTree automatically adds the Google fonts to the head. I can only assume your theme has filtered it off, because this appears to be an issue with your theme and how you setup OptionTree. In my testing environment I can add your specific font without any issues.

**Comment by InspiryThemes** [comment]
Oh!! i found it when you use Latin with "Shadows Into Light" font then Google fonts stylesheet is not adding in head but when you use regular then it adding up.

http://prntscr.com/96pha5

Kindly check it

Thanks

**Comment by InspiryThemes** [comment]
Also it is not working when you didn't select any of them

**Comment by valendesigns** [comment]
I only selected latin during my testing, and it worked for me without any issues.

**Comment by valendesigns** [comment]
I can't look into this anymore today, but I'll check again without any other fonts being added and see if that makes a difference.

**Comment by InspiryThemes** [comment]
Well, thanks a lot for your time and I'll also look into my code and let you know if i find something.
Nice you talk to you :+1:

**Comment by gerardbm** [comment]
I checked it, as well. I think it's not an issue.
 
Every Google Font has two types of options separated in two columns: the first column is the style (weight and style: regular, bold, 300italic, 600...) and the second one are the character sets, or script subsets ("latin", "greek", "cyrillic"...). 

So every Google Font type needs at least one option of each column to work. But this is not 100% true, because if you only activate options of the styles (first column), it will load the font using a default value for the script subset (it's "latin"). If you only activate a script subset, the font won't be loaded because it still needs the main option, the style.

That behavior can be deduced taking a look at the following image, from http://google.com/fonts.

![Google Fonts form](http://i.imgur.com/Q2Pnbfx.png?1)

That explains why it worked when you activated the "regular" style and why it didn't work when you activated the "latin" script subset.

However, «[the Google Fonts API provides the regular version of the requested fonts by default](https://developers.google.com/fonts/docs/getting_started)», so maybe the plugin could be optimized to use the "regular" style as default to load the font if the user only activates a script subset. (Of course, the default value should be removed when the user activates another style in order to don't slow down the webpage with unused styles).

In my opinion, I wouldn't change anything. I'm gonna write: "make sure you activate one font style" in the description of the Google Font option type.

BTW, @valendesigns; I wanted to open a new issue because the stylesheet is not added after a fresh install of a theme. I have to load the options page once to make it work. But this is another topic.

Regards!
