### ISSUE TITLE
database import after issue (urgent) Serialization issue

### ISSUE THREAD

**Issue by rvpatel** [valendesigns/option-tree#613]
Hello sir,
I have import database on live server.  

It turns out that if there's a ", ', :, or ; in any of the array values the serialization gets corrupted.

**

> Special character &  apostrophe  issue

**
Theme option import data lost. (now import using local server but url issue on links).
As well post meta box data not comes on backend (meta value exits on database).

please help as soon as.
![r1](https://cloud.githubusercontent.com/assets/5517932/13810558/801506b4-eb96-11e5-8f3f-b225dc7c749c.png)
![r2](https://cloud.githubusercontent.com/assets/5517932/13810559/80160ef6-eb96-11e5-8dfe-9905a04a5e08.png)

**Comment by rvpatel** [comment]
This one issue arrived on "list-item" data with metabox. (how we can fix please reply as soon as)
![r3](https://cloud.githubusercontent.com/assets/5517932/13811193/2bc3ea90-eb9a-11e5-93b1-a6dc7f0ae2d5.png)

**Comment by Adhik** [comment]
Hi rvpatel, 
I think it was a common problem related to WP (not just OptionTree - but maybe other theme frameworks as well), because meta boxes are saved on serialization form. Problem will surely happen when your dev site URL has different length with your production site URL, since serialization will stored the string length as well. Let say localhost/example (dev server) with example.com (live server).
I suggest you to use [WP Migrate DB](https://wordpress.org/plugins/wp-migrate-db/) plugin to perform the migration.
It worked for me.
