### ISSUE TITLE
Condition for Checkboxes

### ISSUE THREAD

**Issue by borademircan** [valendesigns/option-tree#640]
Hello, 

I seem to have a problem trying to make conditional toggling with the checkbox field. Here is the code:

``` php
array(
   'id'       => 'conditional_checkbox',
  'label'       => __( 'Conditional Checkbox', 'option-tree' ),
  'std'         => '',
  'type'        => 'checkbox',
    'section'     => 'section_id',
    'operator'    => 'and',
    'choices'     => array( 
        array(
            'value'       => 'choice_a',
            'label'       => __( 'Choice A', 'option-tree' ),
            'src'         => ''
        ),
        array(
            'value'       => 'choice_b',
            'label'       => __( 'Choice B', 'option-tree' ),
            'src'         => ''
        ),
    )
),
array(
    'id'          => 'toggle_field',
    'label'       => __( 'Toggle Field', 'option-tree' ),
    'std'         => '',
    'type'        => 'custom-post-type-select',
    'section'     => 'section_id',
    'post_type'   => 'custom_post_type_id',
    'condition'   => 'conditional_checkbox:contains(choice_a)',
    'operator'    => 'and'
),
```

I also try to use:

``` php
'condition'   => 'conditional_checkbox:is(choice_a)',
```

but both do not work.

What should I be doing wrong? Any help will be appreciated.

**Comment by gerardbm** [comment]
Hi. Could you format the code with indentation and new lines? It's a bit difficult to read. Thanks.

**Comment by borademircan** [comment]
Sorry I could not figure that out :) Maybe it is easier to read this way.

**Comment by borademircan** [comment]
Sorry! Now better I guess, thanks! :)

**Comment by gerardbm** [comment]
Your code is ok and the following condition works in many situations:
```php
'condition'   => 'conditional_checkbox:is(choice_a)',
```
I checked this condition and it works perfectly in the most of option types: `on-off`, `radio`, `radio-images`... These option types have one common factor: they only have one selectable option (only one 'value'). I think it's not possible to use this condition in a `checkbox` option type because it has more than one selectable choice.

Operators `and` and `or` are used to compute logical conditions between different options instead of several choices of one option. (For example: show the option3 if 'option1' is 'off' AND 'option2' is 'enabled').

Perhaps it could be implemented in a `checkbox`. Is it possible, @valendesigns?

**Comment by borademircan** [comment]
Thank you @gerardbm yes I have figured out that conditional statments are only for single choice fields. Multiple choice fields such as a checkbox do not work.

I'll keep updated if I make any modification @valendesigns.
